---
title: "milestone4"
author: "Ryan Graff"
date: "October 11, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lintr)
library(gt)
library(readr)
library(dplyr)
library(glue)
library(knitr)
library(styler)
library(tidyr)
library(readxl)
library(purrr)
library(tibble)
library(stringr)
library(janitor)
library(ggplot2)
library(tidyverse)
```


```{r data import, include=FALSE, echo=FALSE}
draft <- read_xlsx("data/draft_data.xlsx", skip = 1) %>%
  clean_names()
```

```{r plot_data, echo=FALSE}
plot <- draft %>% 
  filter(rd == 1 | 2, pk == 1) %>% 
  select(year, rd, vorp, ws)
  
```

```{r graphic, echo=FALSE, warning=FALSE}
ggplot(plot, aes(x = year, y = vorp, size = ws)) + geom_point(aes(color = factor(rd))) + labs(title = "The title of 'First overall' is not created equal", subtitle = "VORPs and Win Shares of the first overall pick in the NBA draft first and second rounds, 1987-2018") + xlab("Year") + ylab("VORP") + labs(color = "Round", size = "Win Shares")

```

